apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: transformer-custom-footer-extension
spec:
  extensionPointName: template-footer-processor
  className: top.howiehz.halo.transformer.template.TransformerFooterProcessor
  displayName: "TransformerFooterProcessor"
  description: "Transform the page content and place it inside a <halo:footer>"
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: transformer-custom-head-extension
spec:
  extensionPointName: template-head-processor
  className: top.howiehz.halo.transformer.template.TransformerHeadProcessor
  displayName: "TransformerHeadProcessor"
  description: "Transform the page content and place it inside a <head>"
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: transformer-additional-webfilter
spec:
  extensionPointName: additional-webfilter
  className: top.howiehz.halo.transformer.filter.TransformerWebFilter
  displayName: "TransformerWebFilter"
  description: "Transform page content in HTML responses"
