apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: transformer-custom-footer-extension
spec:
  extensionPointName: template-footer-processor
  className: top.howiehz.halo.transformer.template.TransformerFooterProcessor
  displayName: "页面转换器页脚模板处理器"
  description: "转换页面内容，并插入到 <halo:footer> 中"
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: transformer-custom-head-extension
spec:
  extensionPointName: template-head-processor
  className: top.howiehz.halo.transformer.template.TransformerHeadProcessor
  displayName: "页面转换器头部模板处理器"
  description: "转换页面内容，并插入到 <head> 中"
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: transformer-additional-webfilter
spec:
  extensionPointName: additional-webfilter
  className: top.howiehz.halo.transformer.filter.TransformerWebFilter
  displayName: "页面转换器 Web 过滤器"
  description: "转换 HTML 响应中的页面内容"
