apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-transformer-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "页面转换器"
    rbac.authorization.halo.run/display-name: "页面转换查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:transformer:view"]
rules:
  - apiGroups: [ "transformer.howiehz.top" ]
    resources: [ "transformationRules" , "transformationSnippets" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-transformer-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "页面转换器"
    rbac.authorization.halo.run/display-name: "页面转换管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:transformer:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-transformer-view"]
rules:
  - apiGroups: [ "transformer.howiehz.top" ]
    resources: [ "transformationRules" , "transformationSnippets" ]
    verbs: [ "add", "update", "delete" ]