# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: transformer
  annotations:
    store.halo.run/app-id: app-ncyyngrz
spec:
  enabled: true
  requires: ">=2.24.0"
  author:
    name: HowieHz
    website: https://github.com/HowieHz
  logo: logo.svg
  homepage: https://github.com/HowieHz/halo-plugin-transformer#readme
  repo: https://github.com/HowieHz/halo-plugin-transformer
  issues: https://github.com/HowieHz/halo-plugin-transformer/issues
  displayName: "页面转换器"
  description: "支持根据规则修改指定页面内容"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/HowieHz/halo-plugin-transformer/blob/main/LICENSE"