// Generated by scripts/sync-match-rule-contract-artifacts.mjs
// Source: contracts/match-rule-contract-metadata.json

export const MATCH_RULE_NODE_SPECS = {
  GROUP: {
    label: '条件组',
    allowedFields: ['type', 'negate', 'operator', 'children'],
  },
  PATH: {
    label: '页面路径条件',
    allowedFields: ['type', 'negate', 'matcher', 'value'],
  },
  TEMPLATE_ID: {
    label: '模板 ID 条件',
    allowedFields: ['type', 'negate', 'matcher', 'value'],
  },
} as const

export const MATCH_RULE_ENUM_SPECS = {
  TYPE: {
    values: ['GROUP', 'PATH', 'TEMPLATE_ID'],
    joinStyle: 'list',
  },
  BOOLEAN: {
    values: ['true', 'false'],
    joinStyle: 'or',
  },
  OPERATOR: {
    values: ['AND', 'OR'],
    joinStyle: 'or',
  },
  PATH_MATCHER: {
    values: ['ANT', 'REGEX', 'EXACT'],
    joinStyle: 'list',
  },
  TEMPLATE_MATCHER: {
    values: ['REGEX', 'EXACT'],
    joinStyle: 'or',
  },
} as const

export type MatchRuleContractNodeType = keyof typeof MATCH_RULE_NODE_SPECS
export type MatchRuleContractEnumName = keyof typeof MATCH_RULE_ENUM_SPECS

export function allowedFieldsFor(nodeType: MatchRuleContractNodeType) {
  return MATCH_RULE_NODE_SPECS[nodeType].allowedFields
}

export function enumValuesFor(enumName: MatchRuleContractEnumName) {
  return MATCH_RULE_ENUM_SPECS[enumName].values
}

export function formatAllowedFields(nodeType: MatchRuleContractNodeType) {
  return formatQuotedValues(allowedFieldsFor(nodeType))
}

export function formatQuotedValues(values: readonly string[], joinStyle: 'list' | 'or' = 'list') {
  const quoted = values.map((value) =>
    value === 'true' || value === 'false' ? value : `"${value}"`,
  )
  if (quoted.length <= 1) {
    return quoted[0] ?? ''
  }
  if (joinStyle === 'or') {
    if (quoted.length === 2) {
      return `${quoted[0]} 或 ${quoted[1]}`
    }
    return `${quoted.slice(0, -1).join('、')} 或 ${quoted[quoted.length - 1]}`
  }
  return quoted.join('、')
}

export function formatUnsupportedFieldMessage(nodeType: MatchRuleContractNodeType) {
  const spec = MATCH_RULE_NODE_SPECS[nodeType]
  return `不支持该字段；${spec.label}仅支持 ${formatAllowedFields(nodeType)}`
}

export function formatMissingEnumFieldMessage(
  fieldName: string,
  enumName: MatchRuleContractEnumName,
  label = '',
) {
  const spec = MATCH_RULE_ENUM_SPECS[enumName]
  const prefix = label ? `${label}缺少必填字段` : '缺少必填字段'
  return `${prefix} "${fieldName}"；该字段可选值为 ${formatQuotedValues(spec.values, spec.joinStyle)}`
}

export function formatInvalidEnumFieldTypeMessage(enumName: MatchRuleContractEnumName) {
  const spec = MATCH_RULE_ENUM_SPECS[enumName]
  return `必须是字符串；仅支持 ${formatQuotedValues(spec.values, spec.joinStyle)}`
}

export function formatInvalidEnumFieldValueMessage(
  enumName: MatchRuleContractEnumName,
  prefix = '仅支持',
) {
  const spec = MATCH_RULE_ENUM_SPECS[enumName]
  return `${prefix} ${formatQuotedValues(spec.values, spec.joinStyle)}`
}

export function formatInvalidBooleanFieldMessage() {
  return `必须是布尔值；仅支持 ${formatQuotedValues(enumValuesFor('BOOLEAN'), MATCH_RULE_ENUM_SPECS.BOOLEAN.joinStyle)}`
}
