package com.erzbir.halo.injector.core;

import java.util.List;

// Generated by scripts/sync-match-rule-contract-artifacts.mjs
// Source: contracts/match-rule-contract-metadata.json
public final class MatchRuleContractMessages {
    private MatchRuleContractMessages() {
    }

    public static String formatUnsupportedFieldMessage(MatchRule.Type nodeType) {
        NodeTypeSpec spec = nodeTypeSpec(nodeType);
        return "不支持该字段；" + spec.label() + "仅支持 " + formatQuotedValues(spec.allowedFields(), JoinStyle.LIST);
    }

    public static String formatMissingEnumFieldMessage(String fieldName, EnumName enumName, String label) {
        EnumSpec spec = enumSpec(enumName);
        String prefix = label == null || label.isBlank() ? "缺少必填字段" : label + "缺少必填字段";
        return prefix + " \"" + fieldName + "\"；该字段可选值为 "
                + formatQuotedValues(spec.values(), spec.joinStyle());
    }

    public static String formatInvalidEnumFieldTypeMessage(EnumName enumName) {
        EnumSpec spec = enumSpec(enumName);
        return "必须是字符串；仅支持 " + formatQuotedValues(spec.values(), spec.joinStyle());
    }

    public static String formatInvalidEnumFieldValueMessage(EnumName enumName) {
        EnumSpec spec = enumSpec(enumName);
        return "仅支持 " + formatQuotedValues(spec.values(), spec.joinStyle());
    }

    public static String formatInvalidBooleanFieldMessage() {
        EnumSpec spec = enumSpec(EnumName.BOOLEAN);
        return "必须是布尔值；仅支持 " + formatQuotedValues(spec.values(), spec.joinStyle());
    }

    public static List<String> allowedFieldsFor(MatchRule.Type nodeType) {
        return nodeTypeSpec(nodeType).allowedFields();
    }

    public static List<String> enumValuesFor(EnumName enumName) {
        return enumSpec(enumName).values();
    }

    private static NodeTypeSpec nodeTypeSpec(MatchRule.Type nodeType) {
        return switch (nodeType) {
            case GROUP -> new NodeTypeSpec("条件组", List.of("type", "negate", "operator", "children"));
            case PATH -> new NodeTypeSpec("页面路径条件", List.of("type", "negate", "matcher", "value"));
            case TEMPLATE_ID -> new NodeTypeSpec("模板 ID 条件", List.of("type", "negate", "matcher", "value"));
        };
    }

    private static EnumSpec enumSpec(EnumName enumName) {
        return switch (enumName) {
            case TYPE -> new EnumSpec(List.of("GROUP", "PATH", "TEMPLATE_ID"), JoinStyle.LIST);
            case BOOLEAN -> new EnumSpec(List.of("true", "false"), JoinStyle.OR);
            case OPERATOR -> new EnumSpec(List.of("AND", "OR"), JoinStyle.OR);
            case PATH_MATCHER -> new EnumSpec(List.of("ANT", "REGEX", "EXACT"), JoinStyle.LIST);
            case TEMPLATE_MATCHER -> new EnumSpec(List.of("REGEX", "EXACT"), JoinStyle.OR);
        };
    }

    private static String formatQuotedValues(List<String> values, JoinStyle joinStyle) {
        List<String> quoted = values.stream()
                .map(value -> "true".equals(value) || "false".equals(value) ? value : "\"" + value + "\"")
                .toList();
        if (quoted.isEmpty()) {
            return "";
        }
        if (quoted.size() == 1) {
            return quoted.getFirst();
        }
        if (joinStyle == JoinStyle.OR) {
            if (quoted.size() == 2) {
                return quoted.get(0) + " 或 " + quoted.get(1);
            }
            return String.join("、", quoted.subList(0, quoted.size() - 1))
                    + " 或 " + quoted.get(quoted.size() - 1);
        }
        return String.join("、", quoted);
    }

    public enum EnumName {
        TYPE,
        BOOLEAN,
        OPERATOR,
        PATH_MATCHER,
        TEMPLATE_MATCHER
    }

    private enum JoinStyle {
        LIST,
        OR
    }

    private record NodeTypeSpec(String label, List<String> allowedFields) {
    }

    private record EnumSpec(List<String> values, JoinStyle joinStyle) {
    }
}
