name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@3af7971b8ff5bf815f703bddce89149826da8a45 # https://github.com/halo-sigs/reusable-workflows/tree/v4
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      ui-path: "ui"
      pnpm-version: "12.3.4"
      node-version: 24
      java-version: 21
      app-id: app-ncyyngrz
