name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@045a5dd72c61775ea923c0a3a58576f680143430 # https://github.com/halo-sigs/reusable-workflows/tree/v4
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      ui-path: "ui"
      pnpm-version: "12.3.4"
      node-version: 24
      java-version: 21
      app-id: app-ncyyngrz
